name: record_ios
description: iOS implementation for record package called by record_platform_interface.
version: 1.1.4
homepage: https://github.com/rostislave23/record_none_audiofocus/tree/master/record_ios

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_platform_interface

flutter:
  plugin:
    implements: record
    platforms:
      ios:
        pluginClass: RecordIosPlugin
