name: record_web
description: Web specific implementation for record package called by record_platform_interface.
version: 1.2.1
homepage: https://github.com/rostislave23/record_none_audiofocus/tree/master/record_web

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  web: ^1.0.0

  record_platform_interface:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_platform_interface

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RecordPluginWeb
        fileName: 'record_web.dart'
  assets:
    - assets/js/record.worklet.js
    - assets/js/record.fixwebmduration.js
