name: record
description: Audio recorder from microphone to file or stream with multiple codecs, bit rate and sampling rate options.
version: 6.1.2
homepage: https://github.com/rostislave23/record_none_audiofocus/tree/master/record

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_platform_interface

  record_web:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_web

  record_windows:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_windows

  record_linux:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_linux

  record_android:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_android

  record_ios:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_ios

  record_macos:
    git:
      url: https://github.com/rostislave23/record_none_audiofocus
      path: record_macos
